version: "3.8"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pact-dev-db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword