#!/bin/sh

if [ "$1" = "-m" ]; then
    tailwindcss -i public/css/main.css -o public/css/dist/output.css --watch --minify
else
    tailwindcss -i public/css/main.css -o public/css/dist/output.css --watch
fi
